
abstract=
ontologyTitle=Digimon Ontology
ontologyPrefix=dig
ontologyNamespaceURI=https://w3id.org/doisr/group3/digimon#
ontologyName=Digimon Ontology
thisVersionURI=https://w3id.org/doisr/group3/digimon/1.1.0
latestVersionURI=
previousVersionURI=https://w3id.org/doisr/group3/digimon/1.0.0
dateCreated=2026-04-16
dateModified=
ontologyRevisionNumber=1.1.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs=Ana García López de Asiain, Mendo Urraca Torrijos, Raúl Reyes Gómez, Álvaro García-Caro Bartolomé. Digimon Ontology. Revision: 1.1.0. Retrieved from: https://w3id.org/doisr/group3/digimon/1.1.0
DOI=
status=Ontology Specification Draft
logo=
description=Ontology for modeling Digimon, their stages, types, attributes, abilities and digivolution paths.
introduction=
backwardsCompatibleWith=https://w3id.org/doisr/group3/digimon/1.0.0
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Ana García López de Asiain;Mendo Urraca Torrijos;Raúl Reyes Gómez;Álvaro García-Caro Bartolomé
authorsURI=;;;
authorsInstitution=;;;
authorsInstitutionURI=;;;
contributors=Ana García López de Asiain;Mendo Urraca Torrijos;Raúl Reyes Gómez;Álvaro García-Caro Bartolomé
contributorsURI=;;;
contributorsInstitution=;;;
contributorsInstitutionURI=;;;
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
